  include "../constants.asm"
  org #0000
xracing_ending_song:
  db 7,184
xracing_ending_song_loop:
  db MUSIC_CMD_REPEAT, 4
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO_SOFT, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 28
  db 9, 0
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO_SOFT, 1
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 30
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 34
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_END_REPEAT
  db MUSIC_CMD_REPEAT, 4
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 32
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 1
  db 9, 0
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO_SOFT, 1
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 39
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_END_REPEAT
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 42
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 2
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 44
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 30
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 28
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 28
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 40
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 42
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 28
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 40
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 32
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 36
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 32
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 32
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 5
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 32
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 32
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 32
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 42
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 44
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 30
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 28
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 28
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 28
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 30
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 38
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 34
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 28
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 36
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 32
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 43
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 32
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 32
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 5
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 32
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 17
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 32
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 33
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 39
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 32
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_GOTO
  dw (xracing_ending_song_loop - xracing_ending_song)
