  include "../constants.asm"
  org #0000
xracing_title_song:
  db 7,184
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 10
  db 9, 0
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 1
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 19
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 10
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 19
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 23
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 10
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 19
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2 + MUSIC_CMD_TIME_STEP_FLAG, 21
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 12
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 12
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 15
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 15
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 14
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 20
  db MUSIC_CMD_PLAY_SFX_OPEN_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 14
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 10
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_SFX_PEDAL_HIHAT + MUSIC_CMD_TIME_STEP_FLAG
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 12
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
xracing_title_song_loop:
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 1
  db 9, 0
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_GOTO
  dw (xracing_title_song_loop - xracing_title_song)
