  org #0000
  include "tiles-ending.asm"
text:
  db "  CONGRATULATIONS!  "
  db " YOU MADE IT TO THE "
  db "  HALL OF FAME OF   "
  db "    FORMULA 1!!     "
  db "                    "
  db "THANK YOU VERY MUCH "
  db "FOR PLAYING XRACING!"
  db "                    "
  db "   SANTI  ONTANON   "
  db "  BRAIN GAMES 2019  "
  db "                    "
  db "THANKS TO THE ORGA- "
  db "NIZERS OF THE MSXDEV"
  db "2018 FOR THE MOTIVA-"
  db "TION FOR NEW GAMES! "
  db "                    "
  db " AND TO EVERYONE IN "
  db " THE 8BIT COMMUNITY "
  db "FOR KEEPING THE MSX "
  db "ALIVE!!             "
  db "                    "
  db "                    "
  db "                    "
  db "                    "
